//! Build script for the kakei_database crate.
//!
//! This script ensures that the crate is recompiled whenever database migrations change.

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=db/migrations");
}
